version: "2"

linters:
  disable:
    - errcheck
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert

linters-settings:
  govet:
    enable:
      - shadow

  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - govet

run:
  timeout: 5m
  tests: true
