version: "2"

linters:
  disable-all: true
  enable:
    # Comprehensive list of strict linters
    - asasalint          # Check for pass []any as any in variadic func(...any)
    - asciicheck         # Check for non-ASCII identifiers
    - bidichk            # Check for dangerous unicode character sequences
    - bodyclose          # Check whether HTTP response body is closed successfully
    - containedctx       # Detects struct that contains context.Context
    - contextcheck       # Check whether the function uses a non-inherited context
    - decorder           # Check declaration order and count of types, constants, variables and functions
    - dogsled            # Check for too many blank identifiers (e.g., x, _, _, _, := f())
    - dupl               # Tool for code clone detection
    - durationcheck      # Check for two durations multiplied together
    - errcheck           # Check for unchecked errors
    - errchkjson         # Check types passed to json encoding functions
    - errname            # Check that sentinel errors are prefixed with Err and error types are suffixed with Error
    - errorlint          # Find code that will cause problems with Go 1.13+ error wrapping
    - exhaustive         # Check exhaustiveness of enum switch statements
    - forbidigo          # Forbid specific identifiers
    - gochecknoinits     # Check that no init functions are present
    - goconst            # Find repeated strings that could be replaced by a constant
    - gocritic           # Comprehensive Go source code linter
    - godot              # Check if comments end in a period
    - godox              # Detect FIXME, TODO and other comment keywords
    - goheader           # Check if file headers match a pattern
    - gomoddirectives    # Manage the use of 'replace', 'retract', and 'excludes' directives in go.mod
    - gomodguard         # Check for blocked dependencies
    - goprintffuncname   # Check that printf-like functions are named with f at the end
    - gosec              # Inspect source code for security problems
    - govet              # Reports suspicious constructs
    - grouper            # Analyze expression groups
    - importas           # Enforce consistent import aliases
    - ineffassign        # Detect ineffectual assignments
    - interfacebloat     # Check the number of methods inside an interface
    - loggercheck        # Check key-value pairs for common logger libraries
    - makezero           # Find slice declarations with non-zero initial length
    - misspell           # Find commonly misspelled English words in comments
    - nakedret           # Find naked returns in functions greater than a specified function length
    - nestif             # Report deeply nested if statements
    - nilerr             # Find code that returns nil even if it checks that the error is not nil
    - nilnil             # Check that there is no simultaneous return of nil error and an invalid value
    - noctx              # Find sending http request without context.Context
    - nolintlint         # Report ill-formed or insufficient nolint directives
    - nosprintfhostport  # Check for misuse of Sprintf to construct a host with port in a URL
    - prealloc           # Find slice declarations that could potentially be pre-allocated
    - predeclared        # Find code that shadows one of Go's predeclared identifiers
    - promlinter         # Check Prometheus metrics naming via promlint
    - reassign           # Check that package variables are not reassigned
    - revive             # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - rowserrcheck       # Check whether Err of rows is checked successfully
    - sqlclosecheck      # Check that sql.Rows and sql.Stmt are closed
    - staticcheck        # Go vet on steroids
    - tagliatelle        # Check struct tags
    - testableexamples   # Check if examples are testable
    - testpackage        # Make you use a separate _test package
    - thelper            # Detect test helpers without t.Helper() call
    - tparallel          # Detect inappropriate usage of t.Parallel() method
    - unconvert          # Remove unnecessary type conversions
    - unparam            # Report unused function parameters
    - unused             # Check for unused constants, variables, functions and types
    - usestdlibvars      # Detect the possibility to use variables/constants from stdlib
    - wastedassign       # Find wasted assignment statements
    - whitespace         # Detection of leading and trailing whitespace
    - wrapcheck          # Check that errors from external packages are wrapped

linters-settings:
  govet:
    enable-all: true
    
  staticcheck:
    checks: ["all"]
    
  revive:
    rules:
      - name: var-naming
        disabled: false
      - name: exported
        disabled: false
      - name: package-comments
        disabled: false
      - name: indent-error-flow
        disabled: false
      - name: blank-imports
        disabled: false
        
  nestif:
    min-complexity: 5
    
  goconst:
    min-len: 3
    min-occurrences: 3
    
  misspell:
    locale: US
    
  godot:
    scope: declarations
    capital: true
    
  errcheck:
    check-type-assertions: true
    check-blank: true
    
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
      
  gosec:
    excludes:
      - G104 # Errors unhandled (duplicates errcheck)
      
  nakedret:
    max-func-lines: 30
    
  prealloc:
    simple: true
    range-loops: true
    for-loops: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:

    # Tests can have long functions
    - path: _test\.go
      linters:
        - dupl


run:
  timeout: 10m
  tests: true
  modules-download-mode: readonly
